import type { Metadata } from "next";
import "./globals.css";
import { FontWrapper } from "@/components/font-wrapper";

export const metadata: Metadata = {
  title: "Jonadrew Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FontWrapper>{children}</FontWrapper>
    </html>
  );
}
