import "./globals.css";
import { Barlow, Gantari, Overpass_Mono } from "next/font/google";
import type { Metadata } from "next";

const barlow = Barlow({
  variable: "--font-header-barlow",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const gantari = Gantari({
  variable: "--font-body-gantari",
  subsets: ["latin"],
});

const overpassMono = Overpass_Mono({
  variable: "--font-overpass-mono",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jonadrew Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${gantari.variable} ${overpassMono.variable} antialiased`}
      >
        {children}{" "}
      </body>
    </html>
  );
}
